services:
  postgres:
    image: postgres:alpine
    container_name: orgv-backend-type2-1.0.0-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - orgv_network

  # Database UI
  adminer:
    image: adminer:latest
    container_name: orgv-backend-type2-1.0.0-adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - orgv_network

  redis:
    image: redis:alpine
    container_name: orgv-backend-type2-1.0.0-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command:
      - "redis-server"
      - "--appendonly yes"
      - "--maxmemory 256mb"
      - "--maxmemory-policy allkeys-lru"
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - orgv_network

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: orgv-backend-type2-1.0.0-redis-commander
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379:0
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - orgv_network

  unleash:
    image: unleashorg/unleash-server:latest
    container_name: orgv-backend-type2-1.0.0-unleash
    restart: unless-stopped
    ports:
      - "4242:4242"
    environment:
      DATABASE_URL: "postgres://postgres:postgres@postgres:5432/unleash_db"
      DATABASE_SSL: "false"
      INIT_ADMIN_API_TOKENS: "*:*.admin-token"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - orgv_network

  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: orgv-backend-type2-1.0.0-rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - orgv_network

networks:
  orgv_network:
    name: orgv_backend_type2_1.0.0_network
    driver: bridge

volumes:
  postgres_data:
    name: orgv_backend_type2_1.0.0_postgres_data
  redis_data:
    name: orgv_backend_type2_1.0.0_redis_data
  rabbitmq_data:
    name: orgv_backend_type2_1.0.0_rabbitmq_data
